export const AUTH_USER = 'AUTH_USER';
export const SAVE_DATA = 'SAVE_DATA';
export const LOAD_DATA = 'LOAD_DATA';
export const FETCH_PERFORMER_DATA = 'FETCH_PERFORMER_DATA';
export const CREATE_PERFORMER = 'CREATE_PERFORMER';
export const UPDATE_PERFORMER = 'UPDATE_PERFORMER';

export const ADD_PERFORMANCE = 'ADD_PERFORMANCE';
export const DELETE_PERFORMANCE = 'DELETE_PERFORMANCE';
export const UPDATE_PERFORMANCE = 'UPDATE_PERFORMANCE';

export const FETCH_GIGS_DATA = 'FETCH_GIGS_DATA';